### ISSUE TITLE
Nothing working here

### ISSUE THREAD

**Issue by aloneguid** [evernote/evernote-sdk-csharp#11]
No matter what I tried I cannot build WP7 project. Windows project builds however crashes with an error on start. 

I give up.

It's a shame because I had a great idea for EverNote integration.

**Comment by fatphil2001** [comment]
There may be other forks that work.  But it looks like this is no longer maintained...

**Comment by mpnow** [comment]
There is a newer Evernote SDK for Windows which is the recommended approach for Windows desktop development. 

Having said that, this SDK also still works fine. I can't speak to WP7 but Windows 7 and 10 work. 

Post your code and specific error info here or on SO if you want some support.

**Comment by aloneguid** [comment]
Blimey, you did respond to my question posted in 2014 🥇 I've moved on from EverNote ages ago, it was a great product for it's time, but not even close to Microsoft OneNote now (IMHO).

**Comment by mpnow** [comment]
Ah OK. Actually I responded to the post made this morning but didn't see that your initial post was old.
